from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import cm
from datetime import datetime, timedelta
import io

IST_OFFSET = timedelta(hours=5, minutes=30)

def generate_completion_report(task, username, owner_email):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm)
    elements = []

    title_style = ParagraphStyle("title", fontSize=22, fontName="Helvetica-Bold", textColor=colors.HexColor("#1e3c72"), spaceAfter=6)
    sub_style = ParagraphStyle("sub", fontSize=10, textColor=colors.grey, spaceAfter=20)
    label_style = ParagraphStyle("label", fontSize=11, fontName="Helvetica-Bold", textColor=colors.HexColor("#333333"), spaceAfter=4)
    value_style = ParagraphStyle("value", fontSize=11, textColor=colors.HexColor("#555555"), spaceAfter=14)
    now_ist = (datetime.utcnow() + IST_OFFSET).strftime("%d %b %Y, %I:%M %p")

    # Header
    elements.append(Paragraph("✅ Task Completion Report", title_style))
    elements.append(Paragraph(f"Completed by: {username}  |  Date: {now_ist}", sub_style))
    elements.append(Spacer(1, 0.3*cm))

    # Green completion banner
    banner_data = [["🎉  TASK SUCCESSFULLY COMPLETED"]]
    banner = Table(banner_data, colWidths=[17*cm])
    banner.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#e8f5e9")),
        ("TEXTCOLOR", (0,0), (-1,-1), colors.HexColor("#2e7d32")),
        ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 14),
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("TOPPADDING", (0,0), (-1,-1), 14),
        ("BOTTOMPADDING", (0,0), (-1,-1), 14),
        ("BOX", (0,0), (-1,-1), 2, colors.HexColor("#43a047")),
        ("ROUNDEDCORNERS", [8,8,8,8]),
    ]))
    elements.append(banner)
    elements.append(Spacer(1, 0.6*cm))

    # Task details table
    elements.append(Paragraph("Task Details", ParagraphStyle("h2", fontSize=13, fontName="Helvetica-Bold", textColor=colors.HexColor("#1e3c72"), spaceAfter=10)))

    due_ist = (task["due_date_raw"] + IST_OFFSET).strftime("%d %b %Y")
    completed_on = now_ist

    details_data = [
        ["Field", "Details"],
        ["Task Title", task["title"]],
        ["Client Name", task["client_name"]],
        ["Client Email", task["client_email"]],
        ["Due Date", due_ist],
        ["Completed On", completed_on],
        ["Completed By", username],
        ["Owner Email", owner_email],
    ]

    details_table = Table(details_data, colWidths=[5*cm, 12*cm])
    details_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e3c72")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 10),
        ("ALIGN", (0,0), (0,-1), "RIGHT"),
        ("FONTNAME", (0,1), (0,-1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0,1), (0,-1), colors.HexColor("#1e3c72")),
        ("BOX", (0,0), (-1,-1), 1, colors.HexColor("#dddddd")),
        ("INNERGRID", (0,0), (-1,-1), 0.5, colors.HexColor("#dddddd")),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#f8f9fa")]),
        ("TOPPADDING", (0,0), (-1,-1), 9),
        ("BOTTOMPADDING", (0,0), (-1,-1), 9),
        ("LEFTPADDING", (0,0), (-1,-1), 10),
    ]))
    elements.append(details_table)
    elements.append(Spacer(1, 0.8*cm))

    # Footer note
    note_style = ParagraphStyle("note", fontSize=9, textColor=colors.grey, alignment=1)
    elements.append(Paragraph("This report was automatically generated by Project Manager Bot upon task completion.", note_style))
    elements.append(Spacer(1, 0.3*cm))
    elements.append(Paragraph(f"© {datetime.utcnow().year} Project Manager Bot", note_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_pdf(tasks, username):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle("title", fontSize=20, fontName="Helvetica-Bold", textColor=colors.HexColor("#1e3c72"), spaceAfter=6)
    sub_style = ParagraphStyle("sub", fontSize=10, textColor=colors.grey, spaceAfter=20)
    now_ist = (datetime.utcnow() + IST_OFFSET).strftime("%d %b %Y, %I:%M %p")

    elements.append(Paragraph("Project Manager Report", title_style))
    elements.append(Paragraph(f"Generated for: {username}  |  Date: {now_ist}", sub_style))
    elements.append(Spacer(1, 0.3*cm))

    total = len(tasks)
    overdue = sum(1 for t in tasks if "OVERDUE" in t.get("status",""))
    urgent = sum(1 for t in tasks if any(x in t.get("status","") for x in ["TODAY","TOMORROW","URGENT"]))
    completed = sum(1 for t in tasks if t.get("is_completed"))
    ontrack = total - overdue - urgent - completed

    summary_data = [
        ["Total Tasks", "Overdue", "Urgent", "On Track", "Completed"],
        [str(total), str(overdue), str(urgent), str(ontrack), str(completed)]
    ]
    summary_table = Table(summary_data, colWidths=[3.5*cm]*5)
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e3c72")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 11),
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("BACKGROUND", (1,1), (1,1), colors.HexColor("#ffebee")),
        ("BACKGROUND", (2,1), (2,1), colors.HexColor("#fff3e0")),
        ("BACKGROUND", (3,1), (3,1), colors.HexColor("#e8f5e9")),
        ("BACKGROUND", (4,1), (4,1), colors.HexColor("#f5f5f5")),
        ("FONTNAME", (0,1), (-1,1), "Helvetica-Bold"),
        ("BOX", (0,0), (-1,-1), 1, colors.HexColor("#dddddd")),
        ("INNERGRID", (0,0), (-1,-1), 0.5, colors.HexColor("#dddddd")),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.6*cm))

    elements.append(Paragraph("Task Details", ParagraphStyle("h2", fontSize=13, fontName="Helvetica-Bold", textColor=colors.HexColor("#1e3c72"), spaceAfter=8)))

    task_data = [["Task Title", "Client", "Due Date", "Time Left", "Status", "Risk"]]
    row_colors = []
    for i, t in enumerate(tasks):
        status = t.get("status", "")
        risk = t.get("risk_label", "")
        risk_short = risk.replace("🔴 HIGH RISK — ", "HIGH: ").replace("🟡 MEDIUM RISK — ", "MED: ").replace("🟢 LOW RISK — ", "LOW: ").replace("🟢 ON TRACK — ", "OK: ").replace("✅ Completed", "Done")
        task_data.append([
            t.get("title","")[:28],
            t.get("client_name","")[:18],
            t.get("due_date",""),
            t.get("time_left",""),
            status.replace("🔴 ","").replace("🟠 ","").replace("🟡 ","").replace("🟢 ","").replace("✅ ",""),
            risk_short[:22]
        ])
        if "OVERDUE" in status:
            row_colors.append(("BACKGROUND", (0, i+1), (-1, i+1), colors.HexColor("#ffebee")))
        elif any(x in status for x in ["TODAY","TOMORROW","URGENT"]):
            row_colors.append(("BACKGROUND", (0, i+1), (-1, i+1), colors.HexColor("#fff8e1")))
        elif t.get("is_completed"):
            row_colors.append(("BACKGROUND", (0, i+1), (-1, i+1), colors.HexColor("#f5f5f5")))
        else:
            row_colors.append(("BACKGROUND", (0, i+1), (-1, i+1), colors.HexColor("#f1f8e9")))

    task_table = Table(task_data, colWidths=[4.5*cm, 3*cm, 2.8*cm, 2.8*cm, 2.8*cm, 3.5*cm], repeatRows=1)
    task_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e3c72")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ALIGN", (0,0), (-1,-1), "LEFT"),
        ("BOX", (0,0), (-1,-1), 1, colors.HexColor("#dddddd")),
        ("INNERGRID", (0,0), (-1,-1), 0.5, colors.HexColor("#dddddd")),
        ("TOPPADDING", (0,0), (-1,-1), 7),
        ("BOTTOMPADDING", (0,0), (-1,-1), 7),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
    ] + row_colors))

    elements.append(task_table)
    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph("Generated by Project Manager Bot", ParagraphStyle("footer", fontSize=8, textColor=colors.grey, alignment=1)))

    doc.build(elements)
    buffer.seek(0)
    return buffer
